### ISSUE TITLE
Suggestion on CMake consumption as non-installed library.

### ISSUE THREAD

**Issue by NouberNou** [mmahnic/argumentum#13]
Hi, recently decided to consume this library as part of a larger project. We generally prefer not to install CMake libraries and distribute all dependencies via git submodules to pin dependency versions and make the building less dependent on users needing to understand/know what the actual dependencies are.

Being able to consume this library via the standard, non-install, CMake syntax of:

```cmake
add_subdirectory(argumentum)
target_link_libraries(my_target PUBLIC argumentum)
```

... would be ideal. This is a more modern way of consuming external dependencies and removes the need for using the global `include_directories` command, which has significant drawbacks in more complex CMake projects.

Would you be open to a pull request reorganizing your CMake to handle this?

Right now, I am getting around this limitation by ignoring the argumentum CMake entirely and consuming it with the following:

```cmake
add_library(argumentum INTERFACE)
target_include_directories(argumentum SYSTEM INTERFACE 3rdparty/argumentum/include)

# ...

target_link_libraries(my_target PUBLIC argumentum)
```

This might also be a suggestion for an alternative piece of documentation in your building documentation in lieu of a reorganization.

**Comment by mmahnic** [comment]
Changes to CMake files have been merged. It should now be possible to use the library as suggested.

The header-only library can be used with

```cmake
add_subdirectory(external/argumentum)
target_link_libraries(my_target PUBLIC Argumentum::headers)
```

If `ARGUMENTUM_BUILD_STATIC_LIBS` variable is set, the static library can be used with

```cmake
add_subdirectory(external/argumentum)
target_link_libraries(my_target PUBLIC Argumentum::argumentum)
```
