### ISSUE TITLE
compile error with basic example and latest master

### ISSUE THREAD

**Issue by chmorgan** [mmahnic/argumentum#6]
ubuntu 21.04, 

g++ --version
g++ (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

``
In file included from /home/cmorgan/projects/a/argumentum/include/argumentum/../../src/value.h:6,
                 from /home/cmorgan/projects/a/argumentum/include/argumentum/../../src/option.h:6,
                 from /home/cmorgan/projects/a/argumentum/include/argumentum/../../src/optionconfig.h:6,
                 from /home/cmorgan/projects/a/argumentum/include/argumentum/../../src/argparser.h:11,
                 from /home/cmorgan/projects/a/argumentum/include/argumentum/argparse.h:6,
                 from /home/cmorgan/projects/a/basic.cpp:2:
/home/cmorgan/projects/a/argumentum/include/argumentum/../../src/convert.h: In instantiation of ‘argumentum::parse_int<int>::<lambda(auto:1)> [with auto:1 = long long unsigned int]’:
/home/cmorgan/projects/a/argumentum/include/argumentum/../../src/convert.h:49:25:   required from ‘T argumentum::parse_int(const string&) [with T = int; std::string = std::__cxx11::basic_string<char>]’
/home/cmorgan/projects/a/argumentum/include/argumentum/../../src/convert.h:130:32:   required from here
/home/cmorgan/projects/a/argumentum/include/argumentum/../../src/convert.h:41:16: error: comparison of integer expressions of different signedness: ‘long long unsigned int’ and ‘int’ [-Werror=sign-compare]
   41 |       if ( res < std::numeric_limits<T>::min() || res > std::numeric_limits<T>::max() )
``

**Comment by mmahnic** [comment]
Fixed in #7.
