### ISSUE TITLE
Specify value name for optional arguments

### ISSUE THREAD

**Issue by NateKomodo** [mmahnic/argumentum#8]
I have the following:

```
params.add_parameter(join, "--join", "-j" )
            .nargs(2)
            .help("Join an existing cluster");
```
which prints the following: `-j, --join JOIN JOIN Join an existing cluster`

I want to set JOIN to something, for each value. I tried to use the metavar, like argprase in python like so: `.metavar("IP CERTPATH")` however that just resulted in `-j, --join IP CERTPATH IP CERTPATH`

**Comment by mmahnic** [comment]
Currently `.metavar()` assumes all arguments are of the same type and it does not analyze the contents of its argument. I will fix the definition of `.metavar()`.
